# This is the name of this workflow, will show up in the Actions tab.
name: Python django CI testing

# This workflow gets triggered on every push to both 'main' and 'dev' branchs.
on:
  push:
    branches:
      - dev

# A workflow run is made up of one or more jobs. This workflow has a single job called 'build'
jobs:
  build:
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    # This sets the default working directory for all steps in this job
    defaults:
      run:
        working-directory: ./backend  # Change this to your Django project directory

    # A job contains a sequence of tasks called 'steps'
    steps:
    # This step checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v2

    # This step sets up the Python version as per the matrix
    - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: "pip"

    # This step installs the dependencies of your Django application
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # This step runs the tests of your Django application
    - name: Run tests
      run: |
        python manage.py test
