name: Django CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" , "dev"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.10", "3.11", "3.12"]
        
    # This sets the default working directory for all steps in this job
    defaults:
      run:
        working-directory: backend  # Change this to your Django project directory

    steps:
    - uses: actions/setup-python@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: createsuperuser
      env: # Or as an environment variable
        DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
      run: |
        python manage.py createsuperuser --username admin --email test@nowhere.com --noinput
    
    - name: makemigrations
      run: |
        python manage.py makemigrations

    - name: migrate
      run: |
        python manage.py migrate
    
    - name: Run Tests
      env: # Or as an environment variable
        super_secret: ${{ secrets.SECRET_KEY }}
      run: |
        python manage.py test
